name: check-code-format
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: npm ci
      - name: prettier
        run: npx prettier --check src/**/*.ts
